import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AppTest {
 @Test
    public void testSmallPrime() {
     App appObj = new App();
     assertEquals(appObj.isPrime(17),true);
 }
    @Test
    public void testNoPrime() {
        App appObj = new App();
        assertEquals(appObj.isPrime(33),false);
    }

    @Test
    public void testLargePrime() {
        App appObj = new App();
        assertEquals(appObj.isPrime(32416189049L),true);
    }

    @Test
    public void testLargeNoPrime() {
        App appObj = new App();
        assertEquals(appObj.isPrime(32416189051L),false);
    }

    @Test
    public void testNumOfPrime() {
        App appObj = new App();
        assertEquals(appObj.CountNumOfPrime(4,100),23);
    }

    @Test
    public void testNumOfPrime2() {
        App appObj = new App();
        assertEquals(appObj.CountNumOfPrime(4,10),2);
    }

    @Test
    public void testNumOfPrime3() {
        App appObj = new App();
        assertEquals(appObj.CountNumOfPrime(1,2),2);
    }

    @Test
    public void testNumOfPrime4() {
        App appObj = new App();
        assertEquals(appObj.CountNumOfPrime(6,6),0);
    }

    @Test
    public void testNumOfPrime5() {
        App appObj = new App();
        assertEquals(appObj.CountNumOfPrime(1,10),5);
    }

    @Test
    public void testPrimeFactor1() {
        List<Integer> list = Arrays.asList(2, 3);
        App appObj = new App();
        assertEquals(appObj.primeFactors(6),list);
    }

    @Test
    public void testPrimeFactor2() {
        List<Integer> list = Arrays.asList(3, 3);
        App appObj = new App();
        assertEquals(appObj.primeFactors(9),list);
    }

    @Test
    public void testPrimeFactor3() {
        List<Integer> list = Arrays.asList(2, 2,2);
        App appObj = new App();
        assertEquals(appObj.primeFactors(8),list);
    }

    @Test
    public void testPrimeFactor4() {
        List<Integer> list = Arrays.asList(2, 5);
        App appObj = new App();
        assertEquals(appObj.primeFactors(10),list);
    }

    @Test
    public void testPrimeFactor5() {
        List<Integer> list = Arrays.asList(2,2,3);
        App appObj = new App();
        assertEquals(appObj.primeFactors(12),list);
    }

    @Test
    public void testPrimeList1() {
         String[] args = {"1","2","3","4","5"};
        List<Long> list = new ArrayList<Long>(Arrays.asList(1L, 2L,3L,5L));
        App appObj = new App();
        assertEquals(appObj.ListOfPrime(args),list);
    }

    @Test
    public void testPrimeList2() {
        String[] args = {"1","7","3","9","5"};
        List<Long> list = new ArrayList<Long>(Arrays.asList(1L, 7L,3L,5L));
        App appObj = new App();
        assertEquals(appObj.ListOfPrime(args),list);
    }

    @Test
    public void testPrimeList3() {
        String[] args = {"1","9","10","13","17"};
        List<Long> list = new ArrayList<Long>(Arrays.asList(1L, 13L,17L));
        App appObj = new App();
        assertEquals(appObj.ListOfPrime(args),list);
    }

    @Test
    public void testPrimeList4() {
        String[] args = {"9","10","34","73","20"};
        List<Long> list = new ArrayList<Long>(Arrays.asList(73L));
        App appObj = new App();
        assertEquals(appObj.ListOfPrime(args),list);
    }

    @Test
    public void testPrimeList5() {
        String[] args = {"10","20","3","40","5"};
        List<Long> list = new ArrayList<Long>(Arrays.asList(3L,5L));
        App appObj = new App();
        assertEquals(appObj.ListOfPrime(args),list);
    }
}
